### ISSUE TITLE
CharacterModelByName allways returns nulls

### ISSUE THREAD

**Issue by CallyyllaC** [KurozeroPB/Kitsu#1]
Not really very good at json, but whenever the `GetCharacterAsync()` method tries to deserialise the json into a `CharacterModelByName` object it returns an object with `id`, `type` and `attributes` all as null.

**Comment by Pepijn98** [comment]
Yea i see what I did wrong, Using GetCharacterAsync() with a character name should return a List. I'm currently working on fixing this.

**Comment by Pepijn98** [comment]
I cant really test right now but i published a 1.0.3-alpha1 to nuget which should fix this.

**Comment by CallyyllaC** [comment]
Yeah that works now, thanks :)
