### ISSUE TITLE
Nsfw support

### ISSUE THREAD

**Issue by xXBuilderBXx** [KurozeroPB/Kitsu#13]
The kitsu website by default does not show nsfw content including the API is there anyway to enable this or login to my account with the wrapper because the attributes for an anime has nsfw value aswell.

**Comment by Pepijn98** [comment]
Huh looking at kitsu's documentation it says indeed that you need to authorize for nsfw content. I'll see what I can do about it.

**Comment by Pepijn98** [comment]
Added an authenticate function, use this to authenticate with your kitsu username and password. After that you can get nsfw content, after 30 days you need to re-authenticate because the token will expire in 30 days.
