### ISSUE TITLE
Improve description on character object

### ISSUE THREAD

**Issue by xXBuilderBXx** [KurozeroPB/Kitsu#16]
Right now the description on characters gives html code you can tidy it up with something like this.
Code: https://pastebin.com/s9b11nKA
Working: https://i.imgur.com/yt6pRWB.png

**Comment by Pepijn98** [comment]
Thanks for reporting, though, I don't think an api wrapper should modify the data returned by the api. If anyone wishes to parse the html elements they can do it.\
I will keep it in mind though for whenever I might change my mind on it.
