### ISSUE TITLE
System.TypeLoadException when used from .NET Framework 4.7.2

### ISSUE THREAD

**Issue by Andis59** [KurozeroPB/Kitsu#19]
I have used NuGet to add Kitsu 1.4.2
If I create a NetCore2.0 console app everything works perfectly
But in .NET 4.7.2 I get this error

```
System.TypeLoadException
HResult=0x80131522
Message=Could not load type 'Kitsu.Anime.AnimeDataModel' from assembly 'Kitsu, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Source=Kitsu
 StackTrace:
   at xKitsu.Program.Main()
   at xKitsu.Program.<Main>()

```

4.7.2 should be Net Standard 2.0 compatible?

Any idea on why and how to fix this?

**Comment by Andis59** [comment]
I found the problem! I had named my project to Kitsu, then changed the Namespace but not the assembly name. So I have my Kitsu.exe and your Kitsu.dll, and that didn't work...

The reason that the netcoreapp2.2 worked was that it had another name...

Sorry for the noise!
Thanks for the library!!

**Comment by Pepijn98** [comment]
I was still searching to find a solution, I'm happy you found a one.
